version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: mdbreact
    versions:
    - "> 4.25.3, < 4.26"
  - dependency-name: react-helmet
    versions:
    - ">= 6.0.a, < 6.1"
  - dependency-name: "@bugsnag/plugin-react"
    versions:
    - 7.5.4
    - 7.6.0
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.2
    - 4.11.3
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: react-scroll
    versions:
    - 1.8.1
  - dependency-name: react-google-recaptcha
    versions:
    - 2.1.0
  - dependency-name: websocket-extensions
    versions:
    - 0.1.4
  - dependency-name: react-router-dom
    versions:
    - 5.2.0
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpmailer/phpmailer
    versions:
    - "> 6.1.4"
